# General knowledge
https://blockgeeks.com/guides/what-is-blockchain-technology/
https://www.coindesk.com/information/what-is-blockchain-technology/

# Trading
# Binance API
https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md
http://python-binance.readthedocs.io/en/latest/binance.html
# Bittrex
https://bittrex.com/home/api
# Gdax
https://www.gdax.com/
# Kraken
https://www.kraken.com/
# Poloniex
https://poloniex.com/
# Bitfinex
https://www.bitfinex.com/
# Algotrading
https://www.algotrader.com/algotrader-4-0-introduces-automated-bitcoin-trading/

# Develop
# etherum
https://www.ethereum.org/
# Blockstack
https://blockstack.org/
# Hyperledger
https://www.hyperledger.org/
# Truffle
http://truffleframework.com/
# uPort
https://www.uport.me/
# Metamask
https://metamask.io/
# ConsenSys
https://new.consensys.net/
# Sovrin
https://sovrin.org/
# Civic
https://www.civic.com/

